# .github/workflows/release.yaml

on:
  release:
    types: [created]

jobs:
  # release-linux-amd64:
  #   name: release linux/amd64
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: wangyoucao577/go-release-action@v1.35
  #       with:
  #         pre_command: export CGO_ENABLED=0
  #         github_token: ${{ secrets.DEPLOY_TOKEN }}
  #         goos: linux
  #         goarch: amd64
  #         goversion: 1.20.1
  #         binary_name: grafana-ntfy-amd64
  #         project_path: ./pkg/
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, linux/arm64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: arm64
            goos: windows
    steps:
      - uses: actions/checkout@v3
      # - uses: wangyoucao577/go-release-action@v1
      - uses: wangyoucao577/go-release-action@v1.35
        with:
          pre_command: export CGO_ENABLED=0
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 1.20.1
          project_path: "./pkg/"
          binary_name: "grafana-ntfy"
