# .github/workflows/release.yaml

on:
  release:
    types: [created]

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.35
        with:
          pre_command: export CGO_ENABLED=0
          github_token: ${{ secrets.DEPLOY_TOKEN }}
          goos: linux
          goarch: amd64
          goversion: 1.20.1
          binary_name: grafana-ntfy
          project_path: ./pkg/
